### ISSUE TITLE
Module no longer passes tests with Date::Time::Locale@1.29 and the install fails

### ISSUE THREAD

**Issue by cthulhu8zombie** [houseabsolute/DateTime-Format-Strptime#28] opened 2020-12-15 16:28 UTC
[build.log](https://github.com/houseabsolute/DateTime-Format-Strptime/files/5697174/build.log)
`Test Summary Report
-------------------
t/basic.t             (Wstat: 512 Tests: 54 Failed: 2)
  Failed tests:  37, 46
  Non-zero exit status: 2
Files=13, Tests=143,  6 wallclock secs ( 0.27 usr  0.05 sys +  4.75 cusr  0.67 csys =  5.74 CPU)
Result: FAIL
Failed 1/13 test programs. 2/143 subtests failed.`

**Comment by autarch** [comment] 2020-12-15 16:40
Actually, this is because of the latest DateTime::TimeZone. I will make an issue in that repo.

**Comment by autarch** [comment] 2020-12-15 16:40
Doh, what am I doing? The issue is in the right repo.

**Comment by autarch** [comment] 2020-12-15 16:41
Double doh. It's too early. This _is_ because of DateTime::Locale.

**Comment by autarch** [comment] 2020-12-15 20:33
This is fixed in v1.78. Thanks for the report!

**Closed by autarch** 2020-12-15 20:33 UTC
